name: autocaption
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  video_player: ^2.9.2
  chewie: ^1.8.5
  image_picker: ^1.1.2
  http: ^1.2.2
  google_generative_ai: ^0.4.6
  path_provider: ^2.1.4
  share_plus: ^10.0.3
  mime: ^2.0.0
  dio: ^5.4.0
  provider: ^6.1.1  # State management
  dropdown_button2: ^2.3.9
  showcaseview: ^3.0.0
  shared_preferences: ^2.2.2
  lucide_icons: ^0.257.0  # Beautiful icons
  google_fonts: ^6.1.0  # Inter font
  gal: ^2.3.2
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

  # Assets
  assets:
    - assets/
    - assets/videos/
    - assets/logo.png
    - assets/Mask Group.png
    - assets/Point_right.png
    - assets/empty.png
    - assets/bomb.png
    - assets/image-1.png
    - assets/image.png

  # Fonts
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/inter.ttf
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
