name: autocaption
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  video_player: ^2.8.1
  chewie: ^1.7.1
  image_picker: ^1.0.4
  http: ^1.1.0
  google_generative_ai: ^0.4.0
  path: ^1.8.3
  mime: ^1.0.4
  ffmpeg_kit_flutter_new_min_gpl: ^2.1.1
  path_provider: ^2.1.1
  share_plus: ^7.2.1
  permission_handler: ^11.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
